# Change these first
owner: SkyfallWasTaken # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Vortex Frontend
    url: https://vortex.skyfall.dev
  - name: Vortex Backend API
    url: https://api.vortex.skyfall.dev
  - name: Vortex SMTP Server
    url: mail.vortex.skyfall.dev
    port: 25
    check: "tcp-ping"
    ipv6: true

assignees: # Users to assign downtime issues (optional)
  - SkyfallWasTaken

status-website:
  cname: status.skyfall.dev
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Skyfall Services
  introTitle: "Uptime monitoring"
  introMessage: "This is the status page for Skyfall's services."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
